output_dir: .

clear_top_level: true
logical_grouping: true

collections:
    - common
    - purescript

loader_paths:
    - docs

render_context:
    project:
        project_name: purescript-grunt
        version: 0.1.0

        verbose_name: PureScript grunt
        description: PureScript FFI bindings for Grunt.

        repository: https://github.com/JoelLefkowitz/purescript-grunt
        codacy_id: 4856ff9fa3ee44b383549476deaaf921

        inserts:
            - usage.md

    author:
        author: Joel Lefkowitz
        author_email: joellefkowitz@hotmail.com
        author_github_handle: joellefkowitz

    package:
        is_pursuit_package: true
        package_name: grunt

    portfolio:
        is_portfolio: true
        status_level: 2

        languages:
            - PureScript

        paradigms:
            - Functional programming
